### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Anastasiagumenuk9** [Anastasiagumenuk9/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Anastasiagumenuk96** [comment]
<section>
								<h3>Skills</h3>
								<p class="tags small"> C# HTML CSS JS NODEJS NPM R<span class="nowrap"> </span>
									<span class="nowrap">MICROSOFT OFFICE</span> PHOTOSHOP VB
									LINUX WINDOWS MYSQL POSTGRESQL SQL</p>
							</section>
							<section>
								<h3>Character</h3>
								<p class="tags small">
									PURPOSEFUL FRIENDLY <a style="color: pink"
										href="https://www.16personalities.com/uk/osobystist-enfp"
										rel="external">ACTIVIST</a> ALTRUIST DEVOTED DEMOCRATIC OPTIMISTIC RESPONSIBLE
									CHALLENGING INQUISITIVE STUBBORN RESPONSIVE</p>
							</section>
							<section>
								<h3>Likes😃</h3>
								<p class="tags small">COMMUNICATION HUMOUR FILMS DOGS PARIS<span class="nowrap"> DA
										VINCIE'S PICTURES </span>
									<span class="nowrap"> MATIOLA FLOWERS </span> SUMMER CHESNUTS
									<button id="pink" class="color pink"> PINK
									</button> <span class="nowrap"> CHILLOUT MUSIC </span> DANCING PSYCHOLOGY CHESS
									<span class="nowrap">ATTENTION TO DETAILS </span>MAFIA GAME<span class="nowrap">
										JOHNNY DEPP </span> <span class="nowrap">STEVE JOBS</span> &#8203;TRAVELS
</section>
<section>
								<h3>Dislikes😞</h3>
								<p class="tags small">LIE POLITICS ARROGANCE BETRAYAL CRUELTY</p>
							</section>
							<section>
								<h3>Wants😊</h3>
								<p class="tags small bulleted"><span class="tag">MY FAMILY BE HEALTHY</span><span
										class="tag">TO IMPROVE MY PROGRAMMING SKILLS</span><span class="tag">TO LISTEN
										AND LEARN</span><span class="tag">TO BUY A CAR</span><span class="tag">TO BE
										HUMANE</span></p>
							</section>
							<section>
								<h3>Education</h3>
								<ul class="timeline">
									<li>
										<div><em>Every day</em></div>
										<p class="tags bulleted">
											<span class="tag"><a style="color: pink"
													href="https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/"
													rel="external"><strong>MSDN</strong></a></span><span class="tag"><a
													style="color: pink" href="https://metanit.com/sharp/"
													rel="external"><strong>METANIT</strong></a></span><span
												class="tag"><a style="color: pink" href="https://moodle.chnu.edu.ua/"
													rel="external"><strong>MOODLE</strong></a></span>
</p>
									</li>
									<li>
										<div><em>1<sup>st</sup> September 2017 – present</em></div>
										<div><strong>Bachelor's degree</strong> in <strong>computer science</strong> at
											<a style="color: pink" href="http://www.chnu.edu.ua/index.php?page=ua"
												rel="external"><strong>Chernivtsi
													National University</strong></a></div>
									</li>
									<li>
										<div><em>1<sup>st</sup> September 2010 – 5<sup>rd</sup> June 2014</em></div>
										<div><strong>Certificate of graduation</strong> at <strong>Khotyn Art
												School</strong></div>
									</li>
									<li>
										<div><em>1<sup>st</sup> September 2006 – 25<sup>st</sup> June 2017</em></div>
										<div><strong>Certificate of graduation</strong> at <strong>№1 Middle School of
												General Education</strong></div>
									</li>
								</ul>
							</section>
<section>
								<h3>Articles</h3>
								<ul class="timeline">
									<li>
										<label for="software-engineer" class="summary">
											Gumenuk A.L. Comparative Characteristic of Intel Processors : materials of
											14<sup>-th</sup> International
											Research And Practice Conference 30<sup>-th</sup> June - 7<sup>-th</sup>
											July 2018 Sheffield : SCIENCE and Education LTO 2018 p.3-5
										</label>
									</li>
									<li>
										<label for="software-engineer" class="summary">
											Gumenuk A.L. Comparative Characteristic of GEFORCE Video Cards : materials
											of 15<sup>-th</sup> International
											Research And Practice Conference 30<sup>-th</sup> May - 7<sup>-th</sup> June
											2019 Sheffield : SCIENCE and Education LTO 2019 p.6-8
										</label>
									</li>
								</ul>
							</section>
