### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Anastasiagumenuk9** [Anastasiagumenuk9/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Anastasiagumenuk96** [comment]
<h3>Experience</h3>
								<h6>Now</h6>
								<ul class="timeline">
									<li>
										<p><em>March 2020 - present</em></p>
										<label for="software-engineer" class="summary">
											<strong>I study remotely and improve my practical and theoretical
												programming knowledge during quarantine</strong>
										</label>
									</li>
								</ul>
								<h6>Way back then</h6>
								<ul class="timeline">
									<li>
										<p><em>1<sup>st</sup> September 2017</em></p>
										<ul>
											<li class="details">
												<input type="checkbox" id="it-production-subdivision-manager">
												<label for="it-production-subdivision-manager" class="summary">
													<strong>Relocated to Chernivtsi</strong>
												</label>
												<div>
													<ul>
														<li>Entered the University</li>
														<li>Settled in a dormitory and found many new friends</li>
													</ul>
												</div>
											</li>
										</ul>
									</li>
									<li>
										<p><em>November 2014</em></p>
										<label for="software-engineer" class="summary">
											<strong>Independently installed </strong> the <strong> Windows XP </strong>
											operating system, YooHoo!
										</label>
									</li>
									<li>
										<p><em>May 2005 - October 2007</em></p>
										<ul>
											<li class="details">
												<input type="checkbox" id="graphic-designer">
												<label for="graphic-designer" class="summary">
													<strong>Hardware Engineer</strong> at <strong>Home</strong>
												</label>
												<div>
													<ul>
														<li>All Dad's tape recorders was disassembled into details</li>
														<li>I tried to make everything as it was, but there were always
															<strong>"extra"</strong> details 🤔</li>
													</ul>
												</div>
											</li>
										</ul>
									</li>
									<li>
										<p><em>16<sup>th</sup> September 2015</em></p>
										<p><strong>Got my internal passport</strong> (with a traditionally awkward
											photo, of course)</p>
									</li>
									<li>
										<p><em>6<sup>th</sup> September 1999</em></p>
										<p><strong>Born</strong> in <strong><a style="color: pink"
													href="https://www.google.com/maps/place/%D0%A5%D0%BE%D1%82%D0%B8%D0%BD,+%D0%A7%D0%B5%D1%80%D0%BD%D1%96%D0%B2%D0%B5%D1%86%D1%8C%D0%BA%D0%B0+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C/@48.5084725,26.4578349,13z/data=!3m1!4b1!4m5!3m4!1s0x4733944a622a3ceb:0x13412835dea98852!8m2!3d48.5097106!4d26.4903334"
													rel="external">Khotyn, Ukraine</a></strong> <sup><em>— Thanks, mom
													and dad!</em></sup></p>
									</li>
								</ul>
