### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Anastasiagumenuk9** [Anastasiagumenuk9/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Anastasiagumenuk96** [comment]
-  https://github.com/Anastasiagumenuk9
- https://t.me/SecretNastya
- Anastasiagumenuk96@gmail.com
- +380967322915
