### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Anastasiagumenuk9** [Anastasiagumenuk9/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Anastasiagumenuk96** [comment]
<p>— Hello! I’m a .NET developer<strong style="margin-left: 0.0625em;">*</strong>. I
										study in CHNU Institute of Physical-Technical and Computer Science. I strive to
										study and practice to improve my programming skills.</p>
									<p style="opacity: 0.9;"><strong style="margin-right: 0.0625em;">*</strong>In future
										😅</p>
